name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Run
      run: go run main.go
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
    - name: Commit
      run: |
        git config --global user.name 'Github'
        git config --global user.email '<>'
        MSG="$(date '+%m.%d @ %H:%M')"
        echo "$MSG"
        git add README.md
        git commit -m "$MSG"
        git push
